### PR TITLE
Add title to generated icons

### PR DESCRIPTION
**Pull request by agawley**
Fixes https://github.com/ismamz/react-bootstrap-icons/issues/13

### CODE REVIEW

**Review by FlorianCassayre — APPROVED** [review]
LGTM

**Comment by FlorianCassayre** [comment]
(give them a week)

**Review by ismamz — APPROVED** [review]

**Comment by FlorianCassayre** [comment]
That was wonderfully quick. Thanks a lot! Looking forward to the release.

**Comment by ismamz** [comment]
@FlorianCassayre @agawley thanks! new release is out!

**Pull request merged**
